<template>

  <blood :graph="state.graph"/>
</template>


<script setup>

import Blood from "./blood.vue";
import {reactive} from "vue";

const state = reactive({
  graph: {
    data: {
      tables: {
        RESULT__T1: {
          id: "T15",
          alias: "",
          name: "RESULT__T1",
          columns: {
            A: "VARCHAR",
            B: "VARCHAR",
            CODE: "VARCHAR",
            C: "VARCHAR",
            D: "VARCHAR",
            ID: "VARCHAR",
          },
          type: "o",
          top: 100,
          left: 1000,
          level: 2,
          groups: [],
          targets: ["T18"],
          metaColumns: {},
          parent: "RESULT",
        },
        RESULT__T2: {
          id: "T16",
          alias: "",
          name: "RESULT__T2",
          columns: {
            CODE: "VARCHAR",
            C: "VARCHAR",
            ID: "VARCHAR",
          },
          type: "o",
          top: 320,
          left: 1000,
          level: 2,
          groups: [],
          targets: ["T18"],
          metaColumns: {},
          parent: "RESULT",
        },
        TAB_2: {
          id: "T11",
          alias: "",
          name: "TAB_2",
          columns: {
            CODE: "VARCHAR",
            C: "VARCHAR",
            ID: "VARCHAR",
          },
          type: "g",
          top: 520,
          left: 600,
          level: 1,
          groups: [],
          targets: ["T16"],
          metaColumns: {},
          parent: "RESULT__T2",
        },
        TAB_3: {
          id: "T12",
          alias: "",
          name: "TAB_3",
          columns: {
            ID: "VARCHAR",
            NAME: "VARCHAR",
          },
          type: "g",
          top: 480,
          left: 1000,
          level: 2,
          groups: [],
          targets: ["T18"],
          metaColumns: {},
          parent: "RESULT",
        },
        TAB_0: {
          id: "T13",
          alias: "",
          name: "TAB_0",
          columns: {
            AA: "VARCHAR",
            COM: "VARCHAR",
            B: "VARCHAR",
            C: "VARCHAR",
            ID: "VARCHAR",
            DESC: "VARCHAR",
          },
          type: "g",
          top: 190,
          left: 200,
          level: 0,
          groups: [],
          targets: ["T17"],
          metaColumns: {},
          parent: "RESULT__T1__U2",
        },
        TAB_1: {
          id: "T14",
          alias: "",
          name: "TAB_1",
          columns: {
            A: "VARCHAR",
            B: "VARCHAR",
            C: "VARCHAR",
            D: "VARCHAR",
            ID: "VARCHAR",
          },
          type: "g",
          top: 410,
          left: 200,
          level: 0,
          groups: [],
          targets: ["T19"],
          metaColumns: {},
          parent: "RESULT__T1__U1",
        },
        RESULT__T1__U2: {
          id: "T17",
          alias: "",
          name: "RESULT__T1__U2",
          columns: {
            A: "VARCHAR",
            B: "VARCHAR",
            CODE: "VARCHAR",
            C: "VARCHAR",
            D: "VARCHAR",
            ID: "VARCHAR",
          },
          type: "o",
          top: 80,
          left: 600,
          level: 1,
          groups: [],
          targets: ["T15"],
          metaColumns: {},
          parent: "RESULT__T1",
        },
        RESULT: {
          id: "T18",
          alias: "",
          name: "RESULT",
          columns: {
            AAA: "VARCHAR",
            CCC: "VARCHAR",
            BBB: "VARCHAR",
            EEE: "VARCHAR",
            DDD: "VARCHAR",
            FFF: "VARCHAR",
          },
          type: "b",
          top: 240,
          left: 1500,
          level: 3,
          groups: [],
          targets: [],
          metaColumns: {},
          parent: null,
        },
        RESULT__T1__U1: {
          id: "T19",
          alias: "",
          name: "RESULT__T1__U1",
          columns: {
            A: "VARCHAR",
            B: "VARCHAR",
            CODE: "VARCHAR",
            C: "VARCHAR",
            D: "VARCHAR",
            ID: "VARCHAR",
          },
          type: "o",
          top: 300,
          left: 600,
          level: 1,
          groups: [],
          targets: ["T15"],
          metaColumns: {},
          parent: "RESULT__T1",
        },
      },
      relations: [
        {
          sourceTable: "T19",
          targetTable: "T15",
          sourceColumn: "A",
          targetColumn: "A",
          type: "A",
        },
        {
          sourceTable: "T19",
          targetTable: "T15",
          sourceColumn: "B",
          targetColumn: "B",
          type: "A",
        },
        {
          sourceTable: "T19",
          targetTable: "T15",
          sourceColumn: "C",
          targetColumn: "C",
          type: "A",
        },
        {
          sourceTable: "T19",
          targetTable: "T15",
          sourceColumn: "D",
          targetColumn: "D",
          type: "A",
        },
        {
          sourceTable: "T19",
          targetTable: "T15",
          sourceColumn: "ID",
          targetColumn: "ID",
          type: "A",
        },
        {
          sourceTable: "T19",
          targetTable: "T15",
          sourceColumn: "CODE",
          targetColumn: "CODE",
          type: "A",
        },
        {
          sourceTable: "T17",
          targetTable: "T15",
          sourceColumn: "A",
          targetColumn: "A",
          type: "A",
        },
        {
          sourceTable: "T17",
          targetTable: "T15",
          sourceColumn: "B",
          targetColumn: "B",
          type: "A",
        },
        {
          sourceTable: "T17",
          targetTable: "T15",
          sourceColumn: "C",
          targetColumn: "C",
          type: "A",
        },
        {
          sourceTable: "T17",
          targetTable: "T15",
          sourceColumn: "D",
          targetColumn: "D",
          type: "A",
        },
        {
          sourceTable: "T17",
          targetTable: "T15",
          sourceColumn: "ID",
          targetColumn: "ID",
          type: "A",
        },
        {
          sourceTable: "T17",
          targetTable: "T15",
          sourceColumn: "CODE",
          targetColumn: "CODE",
          type: "A",
        },
        {
          sourceTable: "T11",
          targetTable: "T16",
          sourceColumn: "C",
          targetColumn: "C",
          type: "A",
        },
        {
          sourceTable: "T11",
          targetTable: "T16",
          sourceColumn: "CODE",
          targetColumn: "CODE",
          type: "A",
        },
        {
          sourceTable: "T11",
          targetTable: "T16",
          sourceColumn: "ID",
          targetColumn: "ID",
          type: "A",
        },
        {
          sourceTable: "T13",
          targetTable: "T17",
          sourceColumn: "AA",
          targetColumn: "A",
          type: "A",
        },
        {
          sourceTable: "T13",
          targetTable: "T17",
          sourceColumn: "B",
          targetColumn: "B",
          type: "A",
        },
        {
          sourceTable: "T13",
          targetTable: "T17",
          sourceColumn: "C",
          targetColumn: "C",
          type: "A",
        },
        {
          sourceTable: "T13",
          targetTable: "T17",
          sourceColumn: "COM",
          targetColumn: "D",
          type: "A",
        },
        {
          sourceTable: "T13",
          targetTable: "T17",
          sourceColumn: "ID",
          targetColumn: "ID",
          type: "A",
        },
        {
          sourceTable: "T13",
          targetTable: "T17",
          sourceColumn: "DESC",
          targetColumn: "CODE",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "A",
          targetColumn: "AAA",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "A",
          targetColumn: "BBB",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "B",
          targetColumn: "BBB",
          type: "A",
        },
        {
          sourceTable: "T16",
          targetTable: "T18",
          sourceColumn: "C",
          targetColumn: "CCC",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "A",
          targetColumn: "DDD",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "A",
          targetColumn: "DDD",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "C",
          targetColumn: "EEE",
          type: "A",
        },
        {
          sourceTable: "T15",
          targetTable: "T18",
          sourceColumn: "A",
          targetColumn: "FFF",
          type: "A",
        },
        {
          sourceTable: "T12",
          targetTable: "T18",
          sourceColumn: "NAME",
          targetColumn: "FFF",
          type: "A",
        },
        {
          sourceTable: "T16",
          targetTable: "T18",
          sourceColumn: "CODE",
          targetColumn: "FFF",
          type: "A",
        },
        {
          sourceTable: "T14",
          targetTable: "T19",
          sourceColumn: "A",
          targetColumn: "A",
          type: "A",
        },
        {
          sourceTable: "T14",
          targetTable: "T19",
          sourceColumn: "B",
          targetColumn: "B",
          type: "A",
        },
        {
          sourceTable: "T14",
          targetTable: "T19",
          sourceColumn: "C",
          targetColumn: "C",
          type: "A",
        },
        {
          sourceTable: "T14",
          targetTable: "T19",
          sourceColumn: "D",
          targetColumn: "D",
          type: "A",
        },
        {
          sourceTable: "T14",
          targetTable: "T19",
          sourceColumn: "ID",
          targetColumn: "ID",
          type: "A",
        },
        {
          sourceTable: "T14",
          targetTable: "T19",
          sourceColumn: "ID",
          targetColumn: "CODE",
          type: "A",
        },
      ],
      tabRelations: [
        {
          sourceTable: "T15",
          targetTable: "T12",
          joinType: null,
          joinColumns: {
            ID: "ID",
          },
          joinColumnsStr: "{ID=ID}",
        },
        {
          sourceTable: "T15",
          targetTable: "T16",
          joinType: null,
          joinColumns: {
            CODE: "CODE",
            ID: "ID",
          },
          joinColumnsStr: "{CODE=CODE, ID=ID}",
        },
      ],
      TABID_DICT: {
        T12: "TAB_3",
        T11: "TAB_2",
        T14: "TAB_1",
        T13: "TAB_0",
        T16: "RESULT__T2",
        T15: "RESULT__T1",
        T18: "RESULT",
        T17: "RESULT__T1__U2",
        T19: "RESULT__T1__U1",
      },
    },
    message: null,
    code: 0,
  }
})
</script>
